/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/gto/preflop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Preflop strategy (presolved)
         * @description Charges 1 presolved quota. The situation (RFI/Limp/Raise/3-Bet/4-Bet/5-Bet) is derived from the actions.
         */
        post: operations["preflopStrategy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/gto/preflop/range": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Whole preflop range for a spot (presolved)
         * @description The full 13×13 preflop range for a position + action line in one call — 169 hand types →
         *     fold/call/raise frequencies. No `hole_cards` (the spot comes from positions +
         *     preflop_actions). Charges 1 presolved quota (one call, not 169). For a range grid.
         */
        post: operations["preflopRange"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/gto/preflop/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List installed preflop strategy versions (free)
         * @description The selectable preflop_version values for /v1/gto/preflop and /v1/gto/preflop/range, with a human label for each and which one is the default (used when preflop_version is omitted). Free (no quota). Use this instead of hardcoding the list — new versions appear here automatically.
         */
        get: operations["preflopVersions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/gto/flop/tree": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Flop decision tree (presolved)
         * @description Charges 1 presolved quota. Returns starting ranges + all decision nodes (each with a token for /v1/gto/flop/node).
         */
        post: operations["flopTree"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/gto/flop/node": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Flop node strategy (presolved) — one decision-tree node
         * @description Per-node strategy for the flop decision tree (free, token-gated). Pass a `node` token minted by POST /v1/gto/flop/tree. With hole_cards → that hand's mixed strategy at the node; omit hole_cards → the node's whole-range strategy.
         *
         *     This is how you get EVERY hero flop decision — hero in position, hero facing a bet, or a later action: fetch the tree, pick a node where is_hero is true (e.g. root/CHECK/BET_13 = hero faces a bet after checking → fold/call/raise), and pass its token here. The root node (root) is hero's first decision (OOP check/bet).
         *
         *     The flop tree is single-street; for turn/river decisions use the solver line (/v1/gto/solver/*).
         */
        post: operations["flopNode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/gto/solver": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Schedule a real-time solve (flop/turn/river)
         * @description board length sets the street (3=flop, 4=turn, 5=river). Charges 1 solve quota on a fresh trigger; a cached solve returns status=queryable with no solve_quota field (not charged); all solver hosts busy returns 429 status=busy with Retry-After and retry_after_ms.
         */
        post: operations["solverSchedule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/gto/solver/tree": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Poll the solve tree + node status (free)
         * @description Poll until spot_status = queryable. To advance a multi-street solve to the dealt runout, pass
         *     the dealt cards: `turn_card` (e.g. a flop solve → a specific turn), and/or `river_card`.
         *     A river spot from a *flop* solve needs BOTH `turn_card` and `river_card` to be unique;
         *     a turn solve needs only `river_card`. Omit both to get the solve's own street.
         */
        post: operations["solverTree"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/gto/solver/node": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Node strategy from a solve (free)
         * @description hero node → hero strategy; villain node (or omit hole_cards) → whole-range strategy.
         */
        post: operations["solverNode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/gto/solver/release": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Release a real-time solve (free, idempotent)
         * @description Best-effort release for a solve handle from /v1/gto/solver. Call this after you finish all tree/node/evs/projected-range queries for the solve, usually in finally. Do not release while you still plan to query the same solve's turn/river subtree.
         */
        post: operations["solverRelease"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/gto/range": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Range conversion — update ranges along an action line
         * @description Thin proxy to the solver's /api/range. You assemble all inputs including solver_results (the decision tree). Charges 1 presolved quota. Output ranges feed the next street's solve.
         */
        post: operations["rangeConvert"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/gto/flop/projected-range": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Projected range — flop range update along an action line (presolved quota)
         * @description Projects the flop ranges forward along an action line for the given board / pot_type / positions. Charges 1 presolved quota. Returns the same range-update output as /v1/gto/range.
         */
        post: operations["projectedRange"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/gto/evs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Node EVs — per-hand, per-action expected values of a completed solve (free)
         * @description Per-hand, per-action expected values at one node of a completed solve. Give the solve handle (from /v1/gto/solver) + a node_id (from /v1/gto/solver/tree); optional hand filters to one hand. Free (already charged via /v1/gto/solver). Poll /v1/gto/solver/tree until queryable first.
         */
        post: operations["queryEvs"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/gto/turn/projected-range": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Projected range — turn→river range update along a turn action line (free)
         * @description The turn→river analog of /v1/gto/flop/projected-range, for a real-time turn solve. Narrows the entering-turn ranges (the ranges the solve was scheduled with, read from the solve's own config) along a turn action line — including the street-closing CALL/CHECK — to the entering-river ranges. Free (the solve was already charged via /v1/gto/solver), like /v1/gto/solver/tree. Returns the same range-update output as /v1/gto/range. Poll /v1/gto/solver/tree until spot_status = queryable first.
         */
        post: operations["turnProjectedRange"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            /** @example missing_api_key */
            error?: string;
            message?: string;
            /** @description optional machine status, e.g. busy for solver pool contention */
            status?: string;
            /** @description optional machine reason, e.g. solver_pool_busy */
            reason?: string;
            /** @description optional retry delay in milliseconds for temporary busy responses */
            retry_after_ms?: number;
        };
        /** @enum {string} */
        Position: "SB" | "BB" | "UTG" | "MP" | "CO" | "BTN";
        /**
         * @description two cards, no separator, e.g. "AdKd". Rank AKQJT98765432, suit c d h s.
         * @example AdKd
         */
        HoleCards: string;
        /**
         * @description community cards as a no-separator string: 3=flop "2c2h2s", 4=turn, 5=river.
         * @example 2c2h2s
         */
        BoardInput: string;
        /**
         * @description community cards returned as an array
         * @example [
         *       "2c",
         *       "2h",
         *       "2s"
         *     ]
         */
        BoardOutput: string[];
        /**
         * @description comma-separated hand:weight. class notation AA/AKs/AKo (high rank first); weight 0..1, default 1.
         * @example AA:1,KK,AKs:0.5,72o:0.1
         */
        RangeString: string;
        Quota: {
            used?: number;
            limit?: number;
        };
        StrategyItem: {
            /** @description check / call / fold / raise / bet */
            action: string;
            /**
             * Format: float
             * @description 0..1 probability
             */
            frequency: number;
            /** @description pot-relative sizing, standard % pot convention: a bet = bet ÷ pot; a raise = (raise − amount-to-call) ÷ pot-after-call. e.g. 0.5 / 0.8 / 1. bet/raise only */
            sizing_pot?: number;
            /** @description absolute bet/raise amount in BB (for bet/raise) */
            amount_bb?: number;
            /** @description present and true when the action is all-in */
            allin?: boolean;
        };
        PreflopRequest: {
            hole_cards: components["schemas"]["HoleCards"];
            positions: {
                hero: components["schemas"]["Position"];
            };
            /** @default 6max */
            table_size: string;
            /**
             * @description optional; which 6max preflop chart set to use. Omit for the platform default (6max). Unknown value -> 400 unsupported_preflop_version.
             * @enum {string}
             */
            preflop_version?: "6max" | "6max_RC_100bb_200NL" | "6max_RC_100bb_100NL" | "6max_RC_40bb";
            /** @description Explicit, complete action sequence from the small blind up to the player right before hero (hero is NOT included; hero's position is positions.hero). Must start with small blind (0.5) then big blind (1). amount is the increment newly committed this action in BB (not the running total); pot = sum of all amounts. A raise's resulting total must exceed the current bet and meet the min-raise (= current bet + size of the last raise) unless allin:true; a call's total must exactly match the current bet unless allin:true. Exact amounts only make the pot/sizing_pot exact — GTO frequencies are situation-based (RFI/3bet/4bet + positions) and do not change with bet sizes. Violations return 400 invalid_actions. */
            preflop_actions: {
                position: components["schemas"]["Position"];
                /** @enum {string} */
                action: "small blind" | "big blind" | "raise" | "call" | "fold";
                /** @description increment newly committed this action in BB (required for non-fold actions); omitted/0 for fold */
                amount?: number;
                /** @description optional; mark a short all-in (raise/call below the min-raise). when true, the min-raise check is skipped */
                allin?: boolean;
            }[];
        };
        PreflopResponse: {
            hole_cards?: string;
            /**
             * @description table state hero faces: RFI (folded to hero, open spot) / Limp (a limper is in, no raise) / Raise (1 raise) / 3-Bet / 4-Bet / 5-Bet
             * @enum {string}
             */
            situation?: "RFI" | "Limp" | "Raise" | "3-Bet" | "4-Bet" | "5-Bet";
            strategy?: components["schemas"]["StrategyItem"][];
            quota?: components["schemas"]["Quota"];
        };
        /** @description required keys depend on pot_type — SRP: hero,raiser,caller; 3BET/4BET: hero,raiser,three_bettor (for 4BET, raiser = the opener who 4-bet, three_bettor = the 3-bettor who called; no four_bettor key); LIMP: hero,limper. hero must be one of the named seats. */
        FlopPositions: {
            hero?: components["schemas"]["Position"];
            raiser?: components["schemas"]["Position"];
            caller?: components["schemas"]["Position"];
            three_bettor?: components["schemas"]["Position"];
            limper?: components["schemas"]["Position"];
        };
        FlopNodeRequest: {
            /** @description node token from /v1/gto/flop/tree (the `token` field of a node) */
            node: string;
            hole_cards?: components["schemas"]["HoleCards"];
        };
        FlopTreeRequest: {
            board: components["schemas"]["BoardInput"];
            /** @enum {string} */
            pot_type: "SRP" | "3BET" | "4BET" | "LIMP";
            positions: components["schemas"]["FlopPositions"];
            /**
             * @description optional; which flop dataset (one solved per preflop version). Omit for the default (6max). If the chosen version has no data for the spot the service degrades gracefully to 6max. Unknown value -> 400 unsupported_flop_version. Independent of preflop_version. The node tokens carry this version, so /v1/gto/flop/node stays on the same dataset.
             * @enum {string}
             */
            flop_version?: "6max" | "6max_RC_100bb_200NL" | "6max_RC_100bb_100NL" | "6max_RC_40bb";
        };
        FlopTreeResponse: {
            board?: components["schemas"]["BoardOutput"];
            pot_type?: string;
            pot?: number;
            effective_stack?: number;
            oop_range?: components["schemas"]["RangeString"];
            ip_range?: components["schemas"]["RangeString"];
            node_count?: number;
            nodes?: {
                /** @example root/CHECK/BET_8 */
                node?: string;
                is_hero?: boolean;
                token?: string;
            }[];
            quota?: components["schemas"]["Quota"];
        };
        /** @description hero node has `strategy`; villain node (or no hole_cards) has `actions` + `range_strategy`. */
        NodeStrategyResponse: {
            node?: string;
            is_hero?: boolean;
            hole_cards?: string;
            strategy?: components["schemas"]["StrategyItem"][];
            actions?: {
                action?: string;
                amount_bb?: number;
                sizing_pot?: number;
                allin?: boolean;
            }[];
            /** @description combo (e.g. "AhKh") -> frequencies aligned to actions */
            range_strategy?: {
                [key: string]: number[];
            };
            range_hand_count?: number;
        };
        SolverScheduleRequest: {
            board: components["schemas"]["BoardInput"];
            oop_range: components["schemas"]["RangeString"];
            ip_range: components["schemas"]["RangeString"];
            pot: number;
            effective_stack: number;
            /** @enum {string} */
            hero: "OOP" | "IP";
            /** @description optional per-street opening bet sizes in pot %; flop defaults to 50% */
            bet_sizes?: {
                flop?: number[];
                turn?: number[];
                river?: number[];
            };
            /** @description optional per-street raise sizes in pot %; omitted streets reuse bet_sizes/defaults */
            raise_sizes?: {
                flop?: number[];
                turn?: number[];
                river?: number[];
            };
            /** @description optional OOP donk-lead sizes in pot %; turn defaults to 67%, river defaults to 100% */
            donk_sizes?: {
                turn?: number[];
                river?: number[];
            };
            /** @description optional tree-wide raise cap; defaults to 3 for flop/turn solves and 4 for river-only solves */
            raise_limit?: number;
        };
        SolverScheduleResponse: {
            /** @enum {string} */
            status?: "computing" | "queryable" | "busy";
            /** @description handle for /tree and /node */
            solve?: string;
            /** @description present only when a new solve was triggered (charged) */
            solve_quota?: components["schemas"]["Quota"];
        };
        SolverReleaseResponse: {
            /** @example success */
            status?: string;
            /** @description true when the coordinator released a registered solve claim */
            released?: boolean;
            /** @description true when the underlying solver slot accepted release */
            solver_released?: boolean;
            /** @description release outcome reason from the solver pool */
            solver_release_reason?: string;
        };
        SolverTreeResponse: {
            /** @enum {string} */
            street?: "flop" | "turn" | "river";
            pot?: number;
            effective_stack?: number;
            /**
             * @description no_nodes = solve converged but the queried round/runout has no decision nodes in the tree (terminal — stop polling).
             * @enum {string}
             */
            spot_status?: "available" | "computing" | "queryable" | "expired" | "no_nodes";
            node_count?: number;
            nodes?: {
                node?: string;
                is_hero?: boolean;
                status?: string;
                token?: string;
            }[];
        };
        RangeRequest: {
            range_oop: components["schemas"]["RangeString"];
            range_ip: components["schemas"]["RangeString"];
            /** @description the decision tree (you assemble it) */
            solver_results: Record<string, never>;
            /** @example root/CHECK/BET 8.000000 */
            node_id: string;
            board?: components["schemas"]["BoardInput"];
            /** @default true */
            normalize: boolean;
            /** @default false */
            explain: boolean;
            track_hands?: string[];
            bluff_discount_ratio?: number;
            /**
             * @description optional card blocking: which player is Hero. Pair with hero_hand.
             * @enum {string}
             */
            hero_position?: "oop" | "ip";
            /**
             * @description optional card blocking: remove every combo containing one of Hero's cards from the ranges (range-vs-hand analysis). Echoed back in the response. Applies to /v1/gto/range only, not the projected-range wrappers.
             * @example AsKs
             */
            hero_hand?: string;
        };
        RangeResponse: {
            range_oop_new?: components["schemas"]["RangeString"];
            range_ip_new?: components["schemas"]["RangeString"];
            range_oop_new_raw?: string;
            range_ip_new_raw?: string;
            range_oop_new_raw_before_normalization?: string;
            range_ip_new_raw_before_normalization?: string;
            /** @description OOP combos by made-hand strength: 'combo:rank,...' (lower rank = stronger), sorted by rank ascending. Equal-rank tie order is NOT guaranteed stable across endpoints/runs — do not depend on it. */
            hand_ranks_oop?: string;
            /** @description IP analog of hand_ranks_oop. */
            hand_ranks_ip?: string;
            /** @description The weakest bluff_combos_ratio fraction of hand_ranks_oop (bluff candidates), same format. */
            hand_bottom_ranks_oop?: string;
            /** @description IP analog of hand_bottom_ranks_oop. */
            hand_bottom_ranks_ip?: string;
            node_id?: string;
            board?: components["schemas"]["BoardOutput"];
            path_length?: number;
            bluff_discount_ratio?: number;
            bluff_combos_ratio?: number;
            quota?: components["schemas"]["Quota"];
        };
        ProjectedRangeRequest: {
            board: components["schemas"]["BoardInput"];
            /** @enum {string} */
            pot_type: "SRP" | "3BET" | "4BET" | "LIMP";
            positions: components["schemas"]["FlopPositions"];
            /**
             * @default root
             * @example root/BET_4
             */
            node_id: string;
            /** @default true */
            normalize: boolean;
            /** @default 0.8 */
            bluff_discount_ratio: number;
            /**
             * @description optional card blocking, pair with hero_hand.
             * @enum {string}
             */
            hero_position?: "oop" | "ip";
            /**
             * @description optional card blocking: remove every combo containing one of Hero's cards from the villain's updated range (the range_*_new_raw outputs). Hero's own hand is also ensured present in Hero's own range. Echoed back.
             * @example AsKs
             */
            hero_hand?: string;
            /** @description optional; fraction of the range treated as bluffs (bottom-of-range). Omit to use the server turn/river default. Echoed back. */
            bluff_combos_ratio?: number;
            /**
             * @description optional; 4-char combos whose cards are removed from the villain's updated range (range_*_new_raw). Requires hero_position. Input only (not echoed). flop/projected-range only.
             * @example [
             *       "Ac9c"
             *     ]
             */
            partner_hands?: string[];
            /**
             * @description optional; which flop dataset (one solved per preflop version). Omit for the default (6max). If the chosen version has no data for the spot the service degrades gracefully to 6max. Unknown value -> 400 unsupported_flop_version. Independent of preflop_version.
             * @enum {string}
             */
            flop_version?: "6max" | "6max_RC_100bb_200NL" | "6max_RC_100bb_100NL" | "6max_RC_40bb";
        };
        /** @description Same fields as RangeResponse, plus pot_type echoed from the request (17 fields total). */
        ProjectedRangeResponse: components["schemas"]["RangeResponse"] & {
            pot_type?: string;
        };
        TurnProjectedRangeRequest: {
            /** @description handle from /v1/gto/solver (a turn solve) */
            solve: string;
            /** @description a turn action line; may end in the street-closing CALL/CHECK. Solver node format with spaces, e.g. "root/CHECK/BET 6.000000/CALL". */
            node_id: string;
            /** @default true */
            normalize: boolean;
            bluff_discount_ratio?: number;
            /**
             * @description optional card blocking, pair with hero_hand.
             * @enum {string}
             */
            hero_position?: "oop" | "ip";
            /**
             * @description optional card blocking: remove every combo containing one of Hero's cards from the villain's updated range.
             * @example AsKs
             */
            hero_hand?: string;
            /**
             * @description optional; 4-char combos whose cards are removed from the villain's updated range. Requires hero_position. Input only.
             * @example [
             *       "Ac9c"
             *     ]
             */
            partner_hands?: string[];
        };
        EvsRequest: {
            /** @description handle from /v1/gto/solver */
            solve: string;
            /**
             * @description a node from /v1/gto/solver/tree (solver notation, e.g. "root/CHECK/BET 6.000000")
             * @example root
             */
            node_id: string;
            /**
             * @description optional; filter to one hand's EVs (else all hands)
             * @example AsKh
             */
            hand?: string;
        };
        /** @description Per-hand, per-action EVs at the node; each hand's EV array aligns with actions. */
        EvsResponse: {
            node_id?: string;
            task_id?: string;
            player?: number;
            /** @example FLOP */
            round?: string;
            /**
             * @example [
             *       "CHECK",
             *       "BET 4.000000",
             *       "BET 97.000000"
             *     ]
             */
            actions?: string[];
            /**
             * @description hand -> per-action EV array (bb); a single array when hand is given
             * @example {
             *       "2c2d": [
             *         -0.826359,
             *         -0.792223,
             *         -1.643411
             *       ]
             *     }
             */
            evs?: {
                [key: string]: number[];
            };
        };
    };
    responses: {
        /** @description invalid input or missing field */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description missing or invalid API key */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description no GTO data for this spot/board */
        NoSolution: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description monthly quota exceeded (resets on the 1st) */
        QuotaExceeded: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description backend temporarily unavailable, retry */
        Upstream: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description solver unreachable after the service's own retries (transport error / 5xx) — retryable; error: upstream_unavailable */
        UpstreamUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description token invalid or not yours */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    preflopStrategy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "hole_cards": "AhKh",
                 *       "positions": {
                 *         "hero": "MP"
                 *       },
                 *       "preflop_version": "6max",
                 *       "preflop_actions": [
                 *         {
                 *           "position": "SB",
                 *           "action": "small blind",
                 *           "amount": 0.5
                 *         },
                 *         {
                 *           "position": "BB",
                 *           "action": "big blind",
                 *           "amount": 1
                 *         },
                 *         {
                 *           "position": "UTG",
                 *           "action": "raise",
                 *           "amount": 3
                 *         }
                 *       ]
                 *     }
                 */
                "application/json": components["schemas"]["PreflopRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreflopResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["QuotaExceeded"];
        };
    };
    preflopRange: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "table_size": "6max",
                 *       "preflop_version": "6max",
                 *       "positions": {
                 *         "hero": "BTN"
                 *       },
                 *       "preflop_actions": [
                 *         {
                 *           "position": "SB",
                 *           "action": "small blind",
                 *           "amount": 0.5
                 *         },
                 *         {
                 *           "position": "BB",
                 *           "action": "big blind",
                 *           "amount": 1
                 *         }
                 *       ]
                 *     }
                 */
                "application/json": {
                    /** @example 6max */
                    table_size: string;
                    /**
                     * @description optional; which 6max preflop chart set to use (same as /v1/gto/preflop). Omit for the default.
                     * @enum {string}
                     */
                    preflop_version?: "6max" | "6max_RC_100bb_200NL" | "6max_RC_100bb_100NL" | "6max_RC_40bb";
                    positions: {
                        /** @example BTN */
                        hero?: string;
                    };
                    /** @description full action sequence from SB/BB, same as /v1/gto/preflop */
                    preflop_actions: Record<string, never>[];
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "range": {
                     *         "AA": {
                     *           "fold": 0,
                     *           "call": 0,
                     *           "raise": 1
                     *         },
                     *         "AKs": {
                     *           "fold": 0,
                     *           "call": 0,
                     *           "raise": 1
                     *         },
                     *         "72o": {
                     *           "fold": 1,
                     *           "call": 0,
                     *           "raise": 0
                     *         }
                     *       },
                     *       "quota": {
                     *         "used": 7,
                     *         "limit": 100
                     *       }
                     *     }
                     */
                    "application/json": {
                        /** @description hand type (AA / AKs / AKo) -> {fold, call, raise}; 169 entries, each summing to ~1 */
                        range?: {
                            [key: string]: {
                                fold?: number;
                                call?: number;
                                raise?: number;
                            };
                        };
                        quota?: {
                            used?: number;
                            limit?: number;
                        };
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NoSolution"];
            429: components["responses"]["QuotaExceeded"];
        };
    };
    preflopVersions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "versions": [
                     *         {
                     *           "id": "6max",
                     *           "label": "6 max 100bb Deepsolver",
                     *           "default": true
                     *         },
                     *         {
                     *           "id": "6max_RC_100bb_200NL",
                     *           "label": "6 max 100bb GG 200NL 3b/f 2.2x - 2.5x"
                     *         },
                     *         {
                     *           "id": "6max_RC_100bb_100NL",
                     *           "label": "6 max 100bb GG 100NL 3b/f"
                     *         },
                     *         {
                     *           "id": "6max_RC_40bb",
                     *           "label": "6 max 40bb GG 100NL"
                     *         }
                     *       ],
                     *       "default": "6max"
                     *     }
                     */
                    "application/json": {
                        versions?: {
                            /** @description pass this as preflop_version */
                            id?: string;
                            label?: string;
                            /** @description present and true on the default version */
                            default?: boolean;
                        }[];
                        /** @description the id used when preflop_version is omitted */
                        default?: string;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    flopTree: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FlopTreeRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlopTreeResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NoSolution"];
            429: components["responses"]["QuotaExceeded"];
        };
    };
    flopNode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "node": "eyJ...<token from /v1/gto/flop/tree>",
                 *       "hole_cards": "AdKd"
                 *     }
                 */
                "application/json": components["schemas"]["FlopNodeRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeStrategyResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NoSolution"];
        };
    };
    solverSchedule: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "board": "2c2h2s9d",
                 *       "oop_range": "AA,KK,QQ,AKs",
                 *       "ip_range": "JJ,TT,AQs,KQs",
                 *       "pot": 20,
                 *       "effective_stack": 90,
                 *       "hero": "OOP",
                 *       "bet_sizes": {
                 *         "turn": [
                 *           67
                 *         ],
                 *         "river": [
                 *           75
                 *         ]
                 *       },
                 *       "raise_sizes": {
                 *         "turn": [
                 *           80
                 *         ],
                 *         "river": [
                 *           125
                 *         ]
                 *       },
                 *       "donk_sizes": {
                 *         "turn": [
                 *           55
                 *         ],
                 *         "river": [
                 *           90
                 *         ]
                 *       },
                 *       "raise_limit": 3
                 *     }
                 */
                "application/json": components["schemas"]["SolverScheduleRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SolverScheduleResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description Solve quota exceeded, or all solver hosts busy. Busy responses use status=busy / error=solver_pool_busy and include Retry-After plus body retry_after_ms; quota errors must not be blindly retried. */
            429: {
                headers: {
                    /** @description seconds to wait before retrying a solver_pool_busy response */
                    "Retry-After"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    solverTree: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "solve": "eyJ0Ijoic2x2X3h4eXoi...(handle from /v1/gto/solver)",
                 *       "turn_card": "Td",
                 *       "river_card": "Qh"
                 *     }
                 */
                "application/json": {
                    /** @description handle from /v1/gto/solver */
                    solve: string;
                    /** @description optional; for a flop solve, the dealt turn card (e.g. "Td") — returns nodes under that turn. */
                    turn_card?: string;
                    /** @description optional; the dealt river card (e.g. "Qh"). From a flop solve, pair with turn_card to disambiguate. */
                    river_card?: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SolverTreeResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            503: components["responses"]["UpstreamUnavailable"];
        };
    };
    solverNode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "node": "eyJ0Ijoic2x2X3h4eXoi...(token from /v1/gto/solver/tree)",
                 *       "hole_cards": "AhKh"
                 *     }
                 */
                "application/json": {
                    /** @description node token from /v1/gto/solver/tree */
                    node: string;
                    hole_cards?: components["schemas"]["HoleCards"];
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeStrategyResponse"] | {
                        /**
                         * @description expired = solve reclaimed/replaced, reschedule; error = solver per-node strategy_error (with message); computing = still solving.
                         * @enum {string}
                         */
                        node_status?: "available" | "computing" | "queryable" | "expired" | "error";
                        /** @description present on node_status = error */
                        message?: string;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            503: components["responses"]["UpstreamUnavailable"];
        };
    };
    solverRelease: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "solve": "eyJ0Ijoic2x2X3h4eXoi...(handle from /v1/gto/solver)"
                 *     }
                 */
                "application/json": {
                    /** @description handle from /v1/gto/solver */
                    solve: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SolverReleaseResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    rangeConvert: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "range_oop": "AA,KK,QQ,JJ,AKs",
                 *       "range_ip": "TT,99,AQs,KQs,JTs",
                 *       "board": "2c2h2s",
                 *       "node_id": "root/CHECK/BET 8.000000",
                 *       "solver_results": {
                 *         "node_type": "action_node",
                 *         "player": 1,
                 *         "strategy": {
                 *           "actions": [
                 *             "CHECK",
                 *             "BET 8.000000"
                 *           ],
                 *           "strategy": {
                 *             "AsAh": [
                 *               0.6,
                 *               0.4
                 *             ]
                 *           }
                 *         },
                 *         "childrens": {
                 *           "CHECK": {
                 *             "node_type": "action_node",
                 *             "player": 0,
                 *             "strategy": {
                 *               "actions": [
                 *                 "CHECK",
                 *                 "BET 8.000000"
                 *               ],
                 *               "strategy": {
                 *                 "KsKh": [
                 *                   0.5,
                 *                   0.5
                 *                 ]
                 *               }
                 *             },
                 *             "childrens": {
                 *               "BET 8.000000": {
                 *                 "node_type": "action_node",
                 *                 "player": 1,
                 *                 "strategy": {
                 *                   "actions": [
                 *                     "FOLD",
                 *                     "CALL",
                 *                     "RAISE 18.000000"
                 *                   ],
                 *                   "strategy": {
                 *                     "QsQh": [
                 *                       0.2,
                 *                       0.5,
                 *                       0.3
                 *                     ]
                 *                   }
                 *                 },
                 *                 "childrens": {}
                 *               }
                 *             }
                 *           }
                 *         }
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["RangeRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RangeResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["QuotaExceeded"];
            502: components["responses"]["Upstream"];
        };
    };
    projectedRange: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "board": "2c2h2s",
                 *       "pot_type": "SRP",
                 *       "positions": {
                 *         "hero": "UTG",
                 *         "raiser": "UTG",
                 *         "caller": "BTN"
                 *       },
                 *       "node_id": "root/BET_4",
                 *       "normalize": true,
                 *       "bluff_discount_ratio": 0.8,
                 *       "bluff_combos_ratio": 0.5,
                 *       "hero_position": "oop",
                 *       "hero_hand": "AsKs",
                 *       "partner_hands": [
                 *         "Ac9c"
                 *       ]
                 *     }
                 */
                "application/json": components["schemas"]["ProjectedRangeRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectedRangeResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NoSolution"];
            429: components["responses"]["QuotaExceeded"];
        };
    };
    queryEvs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "solve": "eyJ0Ijoic2x2X3h4eXoi...(handle from /v1/gto/solver)",
                 *       "node_id": "root"
                 *     }
                 */
                "application/json": components["schemas"]["EvsRequest"];
            };
        };
        responses: {
            /** @description node EVs; or { spot_status: computing } if not converged yet. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvsResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description solve handle invalid or not yours */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description solve expired (TTL); reschedule via /v1/gto/solver */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    turnProjectedRange: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "solve": "eyJ0Ijoic2x2X3h4eXoi...(handle from /v1/gto/solver)",
                 *       "node_id": "root/CHECK/BET 6.000000/CALL",
                 *       "normalize": true
                 *     }
                 */
                "application/json": components["schemas"]["TurnProjectedRangeRequest"];
            };
        };
        responses: {
            /** @description narrowed entering-river ranges; or { spot_status: computing } if the solve has not converged yet (keep polling /v1/gto/solver/tree). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RangeResponse"] | {
                        /** @enum {string} */
                        spot_status?: "computing";
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description solve expired (TTL) — reschedule via /v1/gto/solver */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            502: components["responses"]["Upstream"];
        };
    };
}
